import {isCatalog} from './catalog';
import {estimate,isProject,type Project,type Product} from './project';
export const SELLER_EMAIL='tadekkw123@gmail.com';
export type Inquiry={project:Project;catalog:Product[];name:string;email:string;phone:string;note:string;website:string;requestId:string};
export function isInquiry(v:unknown):v is Inquiry{
 if(!v||typeof v!=='object')return false;const p=v as Inquiry;
 return isProject(p.project)&&p.project.segments.length>0&&p.project.segments.length<=100&&isCatalog(p.catalog)&&typeof p.name==='string'&&p.name.trim().length>=2&&p.name.length<=100&&typeof p.email==='string'&&p.email.length<=254&&/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(p.email)&&!/[\r\n]/.test(p.email)&&typeof p.phone==='string'&&p.phone.length<=40&&typeof p.note==='string'&&p.note.length<=2000&&typeof p.website==='string'&&p.website.length===0&&typeof p.requestId==='string'&&/^[a-z0-9-]{16,80}$/i.test(p.requestId);
}
export function inquiryText(p:Inquiry){const product=p.catalog.find(x=>x.id===p.project.productId)!;const q=estimate(p.project,product);return `Zapytanie o ogrodzenie\n\nKlient: ${p.name}\nE-mail: ${p.email}\nTelefon: ${p.phone||'-'}\nUwagi: ${p.note||'-'}\n\nProjekt: ${p.project.name}\nSystem: ${product.name}\nSzerokość przęsła: ${product.moduleWidth} m\nWysokość: ${p.project.height} m\nŁączna długość: ${q.totalLength.toFixed(2)} m\n\n${q.rows.map(r=>`${r.name}: ${Number(r.quantity.toFixed(2))} ${r.unit} / ${r.total.toFixed(2)} zł`).join('\n')}\nRazem: ${q.total.toFixed(2)} zł brutto\n\nSzacunek z lokalnego konfiguratora, według katalogu dostarczonego przez przeglądarkę. Wymiary i ceny wymagają potwierdzenia sprzedawcy. To zapytanie, nie zamówienie.\n\nOdcinki (poziomy gruntu w metrach):\n${p.project.segments.map((s,i)=>`${i+1}. ${s.kind}, A(${s.a.x},${s.a.y},${s.a.z??0}), B(${s.b.x},${s.b.y},${s.b.z??0})`).join('\n')}`;}
