import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setCornerAngle,cornerAngles,resizeConnected,direction} from '../src/lib/geometry';
import {length,type Segment,initialProject,isProject} from '../src/lib/project';
const square:Segment[]=[{id:'a',kind:'fence',a:{x:0,y:0,z:0},b:{x:10,y:0,z:1}},{id:'b',kind:'fence',a:{x:10,y:0,z:1},b:{x:10,y:10,z:2}},{id:'c',kind:'fence',a:{x:10,y:10,z:2},b:{x:0,y:10,z:0}},{id:'d',kind:'fence',a:{x:0,y:10,z:0},b:{x:0,y:0,z:0}}];
test('editing corner keeps incoming ray and stretches adjacent side of a closed plan',()=>{const result=setCornerAngle(square,'a','b',square[0].b,120);assert.deepEqual(result[0],square[0]);assert.ok(Math.abs(cornerAngles(result).find(c=>c.id==='a:b')!.angle-120)<1e-8);assert.ok(Math.abs(length(result[1])-10)<1e-8);assert.ok(length(result[2])>length(square[2]));assert.deepEqual(result[1].b,result[2].a);assert.deepEqual(result[2].b,square[2].b);assert.equal(result[1].b.z,2);assert.ok(isProject({...initialProject,segments:result}));});
test('corner edit supports reversed rays and keeps topology and elevation',()=>{const reversed=square.map(s=>({...s,a:s.b,b:s.a}));const result=setCornerAngle(reversed,'a','b',square[0].b,60);assert.ok(Math.abs(cornerAngles(result).find(c=>c.id==='a:b')!.angle-60)<1e-8);assert.deepEqual(result[1].a,result[2].b);assert.equal(result[1].a.z,2);});
test('length and direction edits update the neighbour without moving its fixed end',()=>{const result=resizeConnected(square,'a',15,30);assert.ok(Math.abs(length(result[0])-15)<1e-8);assert.ok(Math.abs(direction(result[0])-30)<1e-8);assert.deepEqual(result[0].b,result[1].a);assert.deepEqual(result[1].b,square[1].b);assert.notEqual(length(result[1]),10);});
test('invalid corner constraints and collapsing neighbour are rejected atomically',()=>{for(const angle of [0,-20,181,NaN,Infinity])assert.equal(setCornerAngle(square,'a','b',square[0].b,angle),square);assert.equal(setCornerAngle(square,'a','c',square[0].b,90),square);const triangle:Segment[]=[{id:'a',kind:'fence',a:{x:10,y:0},b:{x:0,y:0}},{id:'b',kind:'fence',a:{x:0,y:0},b:{x:0,y:10}},{id:'c',kind:'fence',a:{x:0,y:10},b:{x:10,y:0}}];assert.equal(setCornerAngle(triangle,'a','b',{x:0,y:0},.01),triangle);});
