'use client';
import {useEffect,useRef,useState} from 'react';
import {inquiryText,SELLER_EMAIL,type Inquiry} from '@/lib/inquiry';
import type {Project,Product} from '@/lib/project';
export default function InquiryForm({project,catalog}:{project:Project;catalog:Product[]}){
 const [enabled,setEnabled]=useState(false),[sending,setSending]=useState(false),[message,setMessage]=useState('');
 const [name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[note,setNote]=useState(''),[website,setWebsite]=useState('');
 const requestId=useRef('');
 useEffect(()=>{requestId.current=crypto.randomUUID();fetch('/api/inquiries').then(r=>r.json()).then(d=>setEnabled(d.enabled===true)).catch(()=>setEnabled(false));},[]);
 const data=():Inquiry=>({project,catalog:catalog.map(p=>({...p,image:undefined})),name,email,phone,note,website,requestId:requestId.current});
 async function send(e:React.FormEvent){e.preventDefault();if(sending)return;setSending(true);setMessage('');try{const res=await fetch('/api/inquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data())});const d=await res.json();setMessage(res.ok?d.message:d.error);if(res.ok)requestId.current=crypto.randomUUID();}catch{setMessage('Brak połączenia z serwerem. Zapytanie nie zostało potwierdzone.');}finally{setSending(false);}}
 return <form className="inquiry-form" onSubmit={send}><h2>Zapytaj sprzedawcę</h2><p>Wyślij konfigurację i poproś o potwierdzenie ceny. To zapytanie, bez zakupu.</p><label>Imię i nazwisko<input required minLength={2} maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>Twój e-mail<input required type="email" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Telefon (opcjonalnie)<input type="tel" maxLength={40} value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Uwagi<textarea maxLength={2000} rows={3} value={note} onChange={e=>setNote(e.target.value)}/></label><label className="honeypot" aria-hidden="true">Strona WWW<input tabIndex={-1} autoComplete="off" value={website} onChange={e=>setWebsite(e.target.value)}/></label><small className="helper">Dane kontaktowe, projekt i PDF trafią do {SELLER_EMAIL}, aby sprzedawca mógł odpowiedzieć na zapytanie.</small><button className="primary" type="submit" disabled={!enabled||sending||!project.segments.length}>{sending?'Wysyłanie…':'Wyślij zapytanie'}</button>{!enabled&&<small className="helper">Wysyłka automatyczna czeka na podłączenie poczty. Możesz teraz otworzyć gotową wiadomość w swoim programie pocztowym i dołączyć pobrany PDF.</small>}<button type="button" disabled={!project.segments.length} onClick={()=>{const content=inquiryText(data());if(content.length>7000){setMessage('Projekt jest zbyt duży do gotowej wiadomości. Pobierz PDF i dołącz go do e-maila do sprzedawcy.');return;}window.location.href=`mailto:${SELLER_EMAIL}?subject=${encodeURIComponent('Zapytanie o ogrodzenie')}&body=${encodeURIComponent(content)}`;}}>Przygotuj e-mail</button>{message&&<p role="status" className="form-message">{message}</p>}</form>;
}

