'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {CATALOG_KEY,isCatalog,readCatalog} from '@/lib/catalog';
import {products,money,type Product} from '@/lib/project';
export default function SellerPanel(){
 const [catalog,setCatalog]=useState(products),[message,setMessage]=useState(''),[loaded,setLoaded]=useState(false);
 useEffect(()=>{setCatalog(readCatalog());setLoaded(true);},[]);
 function update(id:string,field:keyof Product,value:string|number){setCatalog(c=>c.map(p=>p.id===id?{...p,[field]:value}:p));}
 function save(){if(!isCatalog(catalog)){setMessage('Sprawdź wymiary i ceny: szerokość od 0,25 do 6 m; ceny od 0 do 1 000 000 zł.');return;}try{localStorage.setItem(CATALOG_KEY,JSON.stringify(catalog));setMessage('Zapisano wymiary i ceny. Konfigurator korzysta z tych ustawień w tej przeglądarce.');}catch{setMessage('Nie udało się zapisać ustawień w przeglądarce.');}}
 return <div className="admin-shell"><header className="topbar"><Link className="brand" href="/">OGRODZENIA</Link><span className="project-title">Panel sprzedawcy</span><Link className="admin-link" href="/">Wróć do rysunku</Link><button className="primary" disabled={!loaded} onClick={save}>Zapisz ustawienia</button></header><main className="management"><div className="page-heading"><span className="eyebrow">ADMINISTRACJA / PRODUKTY I CENNIKI</span><h1>Katalog i parametry przęseł</h1><p>Ustal szerokość modułu i sposób naliczania ceny. Podział przęseł, słupki i model 3D korzystają z tej samej szerokości.</p></div><div className="admin-notice">Wersja lokalna panelu: ustawienia obowiązują w tej przeglądarce. Udostępnienie panelu wielu sprzedawcom wymaga kont, logowania i bazy danych.</div><div className="catalog-grid">{catalog.map(p=><article className="product-card" key={p.id}><div className={`product-preview ${p.style}`}><div/>{Array.from({length:8},(_,i)=><i key={i}/>)}</div><label>Nazwa produktu<input aria-label={`Nazwa ${p.id}`} maxLength={80} value={p.name} onChange={e=>update(p.id,'name',e.target.value)}/></label><label>Szerokość przęsła<div className="input-unit"><input aria-label={`Szerokość przęsła ${p.id}`} type="number" min="0.25" max="6" step="0.05" value={p.moduleWidth} onChange={e=>update(p.id,'moduleWidth',Number(e.target.value))}/><span>m</span></div></label><label>Rozliczanie przęseł<select aria-label={`Rozliczanie ${p.id}`} value={p.priceMode} onChange={e=>update(p.id,'priceMode',e.target.value)}><option value="meter">Za metr bieżący</option><option value="module">Za pełne przęsło</option></select></label>{([['price',p.priceMode==='module'?'Cena przęsła / szt.':'Cena przęsła / metr'],['postPrice','Cena słupka'],['gatePrice','Cena bramy'],['wicketPrice','Cena furtki']] as const).map(([field,label])=><label key={field}>{label}<div className="input-unit"><input aria-label={`${label} ${p.id}`} type="number" min="0" max="1000000" step="1" value={p[field]} onChange={e=>update(p.id,field,Number(e.target.value))}/><span>zł brutto</span></div></label>)}<p className="helper">Przykład 10 m: {Math.ceil(10/p.moduleWidth)||0} modułów; przęsła {money((p.priceMode==='module'?Math.ceil(10/p.moduleWidth):10)*p.price)}. Końcowy moduł może wymagać przycięcia.</p></article>)}</div><section className="seller-mail"><span className="eyebrow">ZAPYTANIA OD KLIENTÓW</span><h2>tadekkw123@gmail.com</h2><p>Formularz zapytania jest w zakładce Wycena. Automatyczna wysyłka wymaga podłączenia usługi pocztowej na serwerze.</p></section>{message&&<p role="status" className="admin-notice">{message}</p>}<button className="primary" onClick={save}>Zapisz ustawienia</button></main></div>;
}
