'use client';
import dynamic from 'next/dynamic';
import { useEffect, useRef, useState } from 'react';
import { MousePointer2, PenLine, Undo2, Redo2, Trash2, Save, Download, Box, Layers, Ruler, Settings2, FolderOpen, Plus, Minus, Crosshair, Check, X } from 'lucide-react';
import Link from 'next/link';
import InquiryForm from './inquiry-form';
import { quotePdf } from '@/lib/quote-pdf';
import { readCatalog } from '@/lib/catalog';
import { elevation, interpolate, setNodeElevation, splitOpening } from '@/lib/geometry';
import { estimate, initialProject, isProject, length, money, products, type Point, type Project, type Segment } from '@/lib/project';
const Scene = dynamic(() => import('./scene'), { ssr: false, loading: () => <div className="empty">Uruchamianie podglądu 3D…</div> });
const labels = { fence: 'Ogrodzenie', gate: 'Brama', wicket: 'Furtka' };
const key = 'fence-draft-v2';
export default function Workspace() {
 const [project, setProject] = useState<Project>(initialProject);
 const [catalog, setCatalog] = useState(products);
 const [history, setHistory] = useState<Project[]>([]), [future, setFuture] = useState<Project[]>([]);
 const [selected, setSelected] = useState<string | null>(null);
 const [tab, setTab] = useState<'project'|'products'|'quotes'>('project');
 const [view, setView] = useState<'2d'|'3d'>('2d');
 const [tool, setTool] = useState<'select'|'draw'>('select');
 const [drawKind, setDrawKind] = useState<Segment['kind']>('fence');
 const [openingWidth, setOpeningWidth] = useState(4), [openingOffset, setOpeningOffset] = useState(0);
 const [pan,setPan] = useState({x:0,y:0}), [ortho,setOrtho]=useState(true);
 const panDrag=useRef<{x:number;y:number;origin:Point}|null>(null);
 const [showResume,setShowResume]=useState(false);
 const [start, setStart] = useState<Point | null>(null), [cursor, setCursor] = useState<Point | null>(null);
 const [zoom, setZoom] = useState(1), [snap, setSnap] = useState(true), [message, setMessage] = useState('');
 const [ready, setReady] = useState(false);
 const svg = useRef<SVGSVGElement>(null), upload = useRef<HTMLInputElement>(null);
 const product = catalog.find(p => p.id === project.productId) ?? catalog[0];
 const quote = estimate(project, product), active = project.segments.find(s => s.id === selected);
 function notify(text: string) { setMessage(text); }
 function change(next: Project) { setHistory(h => [...h.slice(-49), project]); setFuture([]); setProject(next); }
 function updateSegment(fields: Partial<Segment>) { if (active) change({ ...project, segments: project.segments.map(s => s.id === active.id ? { ...s, ...fields } : s) }); }
 function undo() { const prev = history.at(-1); if (prev) { setFuture(f => [project,...f]); setProject(prev); setHistory(h => h.slice(0,-1)); setStart(null); } }
 function redo() { const next = future[0]; if (next) { setHistory(h => [...h,project]); setProject(next); setFuture(f => f.slice(1)); } }
 function remove() { if (active) { change({ ...project, segments: project.segments.filter(s => s.id !== active.id) }); setSelected(null); } }
 useEffect(() => {
  setCatalog(readCatalog());
  try { const raw=localStorage.getItem(key); setShowResume(!!raw&&isProject(JSON.parse(raw))); } catch {} setReady(true);
  const refresh=()=>setCatalog(readCatalog());window.addEventListener('focus',refresh);window.addEventListener('storage',refresh);
  return ()=>{window.removeEventListener('focus',refresh);window.removeEventListener('storage',refresh);};
 }, []);
 function saveDraft(){try{localStorage.setItem(key,JSON.stringify(project));setShowResume(true);notify('Zapisano projekt. Przy kolejnym otwarciu możesz go wznowić.');}catch{notify('Zapis niedostępny — pobierz plik JSON.');}}
 function resumeDraft(){try{const saved:unknown=JSON.parse(localStorage.getItem(key)??'null');if(isProject(saved)){change(saved);setSelected(null);setShowResume(false);}}catch{notify('Nie można odczytać projektu.');}}
 function chooseDrawing(kind:Segment['kind']){setDrawKind(kind);setTool('draw');setView('2d');setStart(null);if(kind!=='fence')setOpeningWidth(kind==='gate'?4:1);}
 function insertOpening(kind:'gate'|'wicket'){if(!active)return;try{const pieces=splitOpening(active,kind,openingWidth,openingOffset);change({...project,segments:project.segments.flatMap(s=>s.id===active.id?pieces:[s])});setSelected(pieces.find(s=>s.kind===kind)!.id);setStart(null);setTool('select');}catch{notify('Otwór musi mieścić się w odcinku. Sprawdź szerokość i odległość od początku.');}}
 function setGround(node:Point,z:number){if(Number.isFinite(z)&&Math.abs(z)<=20)change({...project,segments:setNodeElevation(project.segments,node,z)});}
 useEffect(() => { if (!message) return; const t = setTimeout(() => setMessage(''), 5000); return () => clearTimeout(t); }, [message]);
 useEffect(() => { function keyboard(e: KeyboardEvent) {
  if ((e.target as HTMLElement).closest('input,select,textarea,button')) return;
  if (e.key === 'Escape') { setStart(null); setTool('select'); }
  if (e.key === 'Delete' || e.key === 'Backspace') { e.preventDefault(); remove(); }
  if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'z') { e.preventDefault(); e.shiftKey ? redo() : undo(); }
  if (e.key.toLowerCase() === 'l') chooseDrawing('fence');
  if (e.key.toLowerCase() === 'g') chooseDrawing('gate');
  if (e.key.toLowerCase() === 'f') chooseDrawing('wicket');
  if (e.key === 'F8') { e.preventDefault();setOrtho(v=>!v); }
  if (e.key.toLowerCase() === 'v') { setTool('select'); setStart(null); }
 } window.addEventListener('keydown',keyboard); return () => window.removeEventListener('keydown',keyboard); });
 function pointer(e: React.PointerEvent<SVGSVGElement>): Point {
  const el = svg.current!; const pt = el.createSVGPoint(); pt.x=e.clientX; pt.y=e.clientY;
  const transformed = pt.matrixTransform(el.getScreenCTM()!.inverse());
  let p = { x: transformed.x/20, y: transformed.y/20 };
  if (snap) { p = {x:Math.round(p.x*2)/2,y:Math.round(p.y*2)/2}; if (start && ortho) { if (Math.abs(p.x-start.x)<.6) p.x=start.x; if (Math.abs(p.y-start.y)<.6) p.y=start.y; } }
  if(start&&ortho){if(Math.abs(p.x-start.x)>Math.abs(p.y-start.y))p.y=start.y;else p.x=start.x;}
  const node=project.segments.flatMap(s=>[s.a,s.b]).find(n=>Math.hypot(n.x-p.x,n.y-p.y)<.3);
  return snap&&node?{...node}:{...p,z:start?elevation(start):0};
 }
 function draw(e:React.PointerEvent<SVGSVGElement>){
  if(e.button===1||e.altKey){e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);panDrag.current={x:e.clientX,y:e.clientY,origin:pan};return;}
  if(tool!=='draw'){setSelected(null);return;}const p=pointer(e);if(!start){setStart(p);return;}
  const l=Math.hypot(start.x-p.x,start.y-p.y);if(l<.25)return;
  const b=drawKind==='fence'?p:interpolate(start,p,openingWidth/l);
  if(project.segments.length>=500||Math.abs(b.x)>500||Math.abs(b.y)>500||Math.abs(start.x)>500||Math.abs(start.y)>500||Math.hypot(b.x-start.x,b.y-start.y)>200){notify('Przekroczono zakres projektu: 500 odcinków, długość do 200 m, współrzędne ±500 m.');return;}
  const s:Segment={id:crypto.randomUUID(),a:start,b,kind:drawKind};change({...project,segments:[...project.segments,s]});setSelected(s.id);setStart(drawKind==='fence'?b:null);
 }
 function move(e:React.PointerEvent<SVGSVGElement>){const drag=panDrag.current;if(drag){const scale=svg.current!.viewBox.baseVal.width/svg.current!.getBoundingClientRect().width;setPan({x:drag.origin.x-(e.clientX-drag.x)*scale,y:drag.origin.y-(e.clientY-drag.y)*scale});}else setCursor(pointer(e));}
 function download(value: unknown, filename: string) { const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})); const a=document.createElement('a'); a.href=url; a.download=filename; a.click(); setTimeout(()=>URL.revokeObjectURL(url),30000); }
 async function downloadPdf(){try{const response=await fetch('/fonts/LiberationSans-Regular.ttf');if(!response.ok)throw Error();const bytes=quotePdf(project,product,new Uint8Array(await response.arrayBuffer()));const url=URL.createObjectURL(new Blob([bytes as Uint8Array<ArrayBuffer>],{type:'application/pdf'}));const link=document.createElement('a');link.href=url;link.download='wycena-ogrodzenia.pdf';link.click();URL.revokeObjectURL(url);}catch{notify('Nie udało się przygotować PDF. Spróbuj ponownie.');}}
 function fit() { setZoom(1); setPan({x:0,y:0}); }
 const previewEnd=start&&cursor&&drawKind!=='fence'?interpolate(start,cursor,openingWidth/Math.max(.001,Math.hypot(cursor.x-start.x,cursor.y-start.y))):cursor;
 const allPoints=project.segments.flatMap(s=>[s.a,s.b]);
 const minX=Math.min(0,...allPoints.map(p=>p.x*20))-70, minY=Math.min(0,...allPoints.map(p=>p.y*20))-70;
 const width=Math.max(680,Math.max(0,...allPoints.map(p=>p.x*20))-minX+70), height=Math.max(480,Math.max(0,...allPoints.map(p=>p.y*20))-minY+70);
 return <div className="app-shell">
 <header className="topbar"><a className="brand" href="/" aria-label="Konfigurator ogrodzeń — strona główna"><span className="brand-word">OGRODZENIA</span><span className="brand-sub">EDYTOR CAD</span></a><div className="project-title"><span className="status-dot" />{project.name}<small>LOKALNY PROJEKT</small></div><button onClick={saveDraft}><Save size={15}/> Zapisz</button><Link className="admin-link" href="/admin" target="_blank" rel="noopener noreferrer">Panel sprzedawcy</Link><button className="primary" onClick={()=>setTab('quotes')}>Wycena <span>↗</span></button></header>
 <nav className="navigation"><div>{(['project','products','quotes'] as const).map((t,i)=><button key={t} className={tab===t?'nav-active':''} onClick={()=>setTab(t)}>{[<Layers size={14} key="a"/>,<Box size={14} key="b"/>,<Ruler size={14} key="c"/>][i]}{['Projekt','Produkty','Wycena'][i]}</button>)}</div><span>EDYTOR / MODEL I WYCENA <b>01</b></span></nav>
 {tab==='project' ? <main className="workspace">
 <aside className="left-panel"><div className="panel-heading">STRUKTURA PROJEKTU <span>{project.segments.length}</span></div><div className="tree-root"><FolderOpen size={15}/><input aria-label="Nazwa projektu" value={project.name} maxLength={80} onChange={e=>change({...project,name:e.target.value})}/></div><div className="segment-list">{project.segments.map((s,i)=><button className={selected===s.id?'segment selected':'segment'} key={s.id} onClick={()=>{setSelected(s.id);setTool('select');setStart(null);}}><span className={`segment-symbol ${s.kind}`} /><span>{labels[s.kind]} <small>{String(i+1).padStart(2,'0')}</small></span><em>{length(s).toFixed(1)} m</em></button>)}</div><button className="add-segment" onClick={()=>{chooseDrawing('fence');setStart(null);}}><Plus size={14}/> Rysuj odcinek</button><div className="left-bottom"><span className="eyebrow">PODSUMOWANIE GEOMETRII</span><div><strong>{quote.totalLength.toFixed(1)}<small> m</small></strong><span>łączna długość</span></div><div className="tiny-stats"><span>{quote.modules} przęseł</span><span>{quote.posts} słupków</span></div></div></aside>
 <section className="viewport-area"><div className="viewport-toolbar"><div><button title="Wybierz (V)" aria-label="Wybierz" className={tool==='select'?'active':''} onClick={()=>{setTool('select');setStart(null);}}><MousePointer2 size={17}/></button><button title="Rysuj odcinki (L)" aria-label="Rysuj odcinki" className={tool==='draw'&&drawKind==='fence'?'active':''} onClick={()=>chooseDrawing('fence')}><PenLine size={17}/><span>Odcinek</span></button><button onClick={()=>chooseDrawing('gate')} className={tool==='draw'&&drawKind==='gate'?'active':''}>Brama</button><button onClick={()=>chooseDrawing('wicket')} className={tool==='draw'&&drawKind==='wicket'?'active':''}>Furtka</button><i/><button title="Cofnij (Ctrl+Z)" aria-label="Cofnij" disabled={!history.length} onClick={undo}><Undo2 size={17}/></button><button title="Ponów" aria-label="Ponów" disabled={!future.length} onClick={redo}><Redo2 size={17}/></button><button title="Usuń zaznaczenie" aria-label="Usuń zaznaczony odcinek" disabled={!active} onClick={remove}><Trash2 size={16}/></button></div><div className="view-switch"><button className={view==='2d'?'active':''} onClick={()=>setView('2d')}>2D / PLAN</button><button className={view==='3d'?'active':''} onClick={()=>{setView('3d');setStart(null);setTool('select');}}>3D / MODEL</button></div></div>
 <div className="drafting-ribbon"><span>RYSUJ</span><button className={ortho?'enabled':''} onClick={()=>setOrtho(v=>!v)}>ORTO {ortho?'ON':'OFF'}</button>{tool==='draw'&&drawKind!=='fence'?<label>Szerokość {drawKind==='gate'?'bramy':'furtki'}<input aria-label="Szerokość nowego otworu" type="number" min="0.5" max="12" step="0.1" value={openingWidth} onChange={e=>{const v=Number(e.target.value);if(v>=.5&&v<=12)setOpeningWidth(v);}}/> m</label>:<span>Siatka 0,5 m · Alt + przeciągnij: przesuń plan</span>}<span className="ribbon-end">WARSTWA: {drawKind==='fence'?'OGRODZENIE':drawKind==='gate'?'BRAMY':'FURTKI'}</span></div>
 <div className={`viewport ${tool==='draw'?'drawing':''}`}><div className="viewport-label"><span>{view==='2d'?'RZUT Z GÓRY':'WIDOK PERSPEKTYWICZNY'}</span><small>{product.name} · wysokość {project.height.toFixed(2)} m · przęsło {product.moduleWidth.toFixed(2)} m</small></div>
 {view==='2d'?<svg ref={svg} role="img" aria-label="Plan ogrodzenia. Kliknij narzędzie rysowania, następnie punkty początku i końca odcinka." viewBox={`${minX+(width-width/zoom)/2+pan.x} ${minY+(height-height/zoom)/2+pan.y} ${width/zoom} ${height/zoom}`} onWheel={e=>setZoom(z=>Math.max(.5,Math.min(3,z+(e.deltaY<0?.1:-.1))))} onPointerDown={draw} onPointerMove={move} onPointerUp={()=>{panDrag.current=null;}} onPointerCancel={()=>{panDrag.current=null;}} onPointerLeave={()=>setCursor(null)}>
 <defs><pattern id="minor" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M 20 0 L 0 0 0 20" fill="none" stroke="#252c32" strokeWidth=".6"/></pattern><pattern id="major" width="100" height="100" patternUnits="userSpaceOnUse"><rect width="100" height="100" fill="url(#minor)"/><path d="M 100 0 L 0 0 0 100" fill="none" stroke="#343c43" strokeWidth=".8"/></pattern></defs><rect x={-20000} y={-20000} width={40000} height={40000} fill="url(#major)"/>
 <path d="M -20000 0 H 20000 M 0 -20000 V 20000" stroke="#41545a" strokeWidth=".8"/><text x="6" y="-8" className="origin">0,0</text>
 {project.segments.map((s,i)=>{const chosen=s.id===selected, ax=s.a.x*20,ay=s.a.y*20,bx=s.b.x*20,by=s.b.y*20;return <g key={s.id} onPointerDown={e=>{if(tool==='select'){e.stopPropagation();setSelected(s.id);}}} className="plan-segment"><line x1={ax} y1={ay} x2={bx} y2={by} stroke="transparent" strokeWidth={18}/><line x1={ax} y1={ay} x2={bx} y2={by} stroke={chosen?'#b7c3ce':s.kind==='fence'?'#a4b3bd':'#8b9da9'} strokeWidth={chosen?5:3} strokeDasharray={s.kind==='fence'?undefined:'8 4'}/><text x={(ax+bx)/2+(ax===bx?-24:0)} y={(ay+by)/2+(ax===bx?0:-16)} textAnchor="middle" className={chosen?'dimension chosen':'dimension'}>{length(s).toFixed(2)} m</text><text x={(ax+bx)/2+(ax===bx?20:0)} y={(ay+by)/2+(ax===bx?0:26)} textAnchor="middle" className="segment-number">{String(i+1).padStart(2,'0')}</text>{[s.a,s.b].map((p,j)=><rect key={j} x={p.x*20-4} y={p.y*20-4} width={8} height={8} fill="#15191d" stroke={chosen?'#b7c3ce':'#a4b3bd'} strokeWidth={1.5}/>)}</g>;})}
 {start&&previewEnd&&<g pointerEvents="none"><line x1={start.x*20} y1={start.y*20} x2={previewEnd!.x*20} y2={previewEnd!.y*20} stroke="#b7c3ce" strokeWidth={2} strokeDasharray="6 4"/><circle cx={previewEnd!.x*20} cy={previewEnd!.y*20} r={5} fill="#b7c3ce"/><text x={previewEnd!.x*20+10} y={previewEnd!.y*20-10} className="dimension chosen">{Math.hypot(previewEnd!.x-start.x,previewEnd!.y-start.y).toFixed(2)} m</text></g>}
 </svg>:<Scene project={project} product={product}/>}
 {!project.segments.length&&view==='2d'&&<div className="empty overlay"><span>Nowy rysunek</span><br/><small>Odcinek: kliknij początek i koniec. Brama / furtka: wybierz narzędzie.</small></div>}
 {showResume&&!project.segments.length&&<button className="resume-draft" onClick={resumeDraft}>Wznów zapisany projekt</button>}<div className="axis"><span>Y</span><b>└── X</b></div><div className="viewport-controls">{view==='2d'&&<><button aria-label="Oddal" onClick={()=>setZoom(z=>Math.max(.5,z-.25))}><Minus size={14}/></button><span>{Math.round(zoom*100)}%</span><button aria-label="Przybliż" onClick={()=>setZoom(z=>Math.min(3,z+.25))}><Plus size={14}/></button><button title="Dopasuj plan" aria-label="Dopasuj plan" onClick={fit}><Crosshair size={15}/></button></>}</div></div>
 <div className="command-bar"><span className="command-indicator">›</span>{view==='3d'?'Przeciągnij, aby obrócić model. Kółko myszy zmienia przybliżenie.':tool==='draw'?(start?(drawKind==='fence'?'Wskaż kolejny punkt · Esc kończy rysowanie':'Wskaż kierunek otworu · długość z pola szerokości'):`${labels[drawKind]}: wskaż punkt początkowy`):'Wybierz odcinek, aby edytować jego właściwości'}<kbd>{tool==='draw'?'ESC':'V / L'}</kbd></div></section>
 <aside className="right-panel"><div className="panel-heading"><span>WŁAŚCIWOŚCI</span><Settings2 size={14}/></div><section className="property-section"><div className="eyebrow">SYSTEM OGRODZENIA</div><label>Produkt<select value={project.productId} onChange={e=>change({...project,productId:e.target.value})}>{catalog.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className={`product-preview ${product.style}`}><div/>{Array.from({length:8},(_,i)=><i key={i}/>)}</div><label>Wysokość <div className="input-unit"><input aria-label="Wysokość ogrodzenia" type="number" min="0.5" max="3" step="0.1" value={project.height} onChange={e=>{const v=Number(e.target.value);if(v>=.5&&v<=3)change({...project,height:v});}}/><span>m</span></div></label><label>Wykończenie<div className="color-options">{[['#454b50','Antracyt'],['#aab0b3','Jasnoszary'],['#382e27','Brąz']].map(([color,name])=><button key={color} title={name} aria-label={name} className={project.color===color?'color selected-color':'color'} style={{background:color}} onClick={()=>change({...project,color})}>{project.color===color&&<Check size={14}/>}</button>)}<span>{project.color==='#454b50'?'RAL 7016':project.color==='#aab0b3'?'RAL 7035':'RAL 8019'}</span></div></label></section>
 <section className="property-section"><div className="eyebrow">{active?`ODCINEK ${String(project.segments.indexOf(active)+1).padStart(2,'0')}`:'ZAZNACZENIE'}</div>{active?<><label>Typ elementu<select value={active.kind} onChange={e=>updateSegment({kind:e.target.value as Segment['kind']})}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Długość<div className="input-unit"><input aria-label="Długość odcinka" type="number" min="0.5" max="100" step="0.5" value={Number(length(active).toFixed(2))} onChange={e=>{const v=Number(e.target.value);if(v<.5||v>100)return;const l=length(active);updateSegment({b:{z:elevation(active.b),x:active.a.x+(active.b.x-active.a.x)*v/l,y:active.a.y+(active.b.y-active.a.y)*v/l}});}}/><span>m</span></div></label><div className="terrain-fields"><div className="eyebrow">POZIOM GRUNTU</div><label>Punkt A<div className="input-unit"><input aria-label="Poziom gruntu w punkcie A" type="number" min="-20" max="20" step="0.1" value={Number(elevation(active.a).toFixed(3))} onChange={e=>setGround(active.a,Number(e.target.value))}/><span>m</span></div></label><label>Punkt B<div className="input-unit"><input aria-label="Poziom gruntu w punkcie B" type="number" min="-20" max="20" step="0.1" value={Number(elevation(active.b).toFixed(3))} onChange={e=>setGround(active.b,Number(e.target.value))}/><span>m</span></div></label><small className="helper">Poziomy względem umownego 0,00 m. Wspólne końce aktualizują się razem. Spadek: {((elevation(active.b)-elevation(active.a))/length(active)*100).toFixed(1)}%.</small>{active.kind!=='fence'&&Math.abs(elevation(active.b)-elevation(active.a))>.05&&<small className="terrain-warning">Otwór na spadku wymaga sprawdzenia prześwitu i wyrównania terenu.</small>}</div><small className="helper">Zmiana długości przesuwa koniec tego odcinka. Sąsiednie odcinki zachowują pozycję.</small><div className="coordinates">A <span>{active.a.x.toFixed(1)} ; {active.a.y.toFixed(1)}</span><br/>B <span>{active.b.x.toFixed(1)} ; {active.b.y.toFixed(1)}</span></div></>:<p className="helper">Wybierz odcinek na planie lub na liście.</p>}</section>
 <section className="property-section opening-section"><div className="eyebrow">DODAJ OTWÓR W ODCINKU</div><label>Szerokość otworu<div className="input-unit"><input aria-label="Szerokość otworu w odcinku" type="number" min="0.5" max="12" step="0.1" value={openingWidth} onChange={e=>{const v=Number(e.target.value);if(v>=.5&&v<=12)setOpeningWidth(v);}}/><span>m</span></div></label><label>Odległość od punktu A<div className="input-unit"><input aria-label="Odległość otworu od początku" type="number" min="0" step="0.1" value={openingOffset} onChange={e=>{const v=Number(e.target.value);if(v>=0&&Number.isFinite(v))setOpeningOffset(v);}}/><span>m</span></div></label><div className="opening-actions"><button disabled={!active||active.kind!=='fence'} onClick={()=>insertOpening('gate')}>Wstaw bramę</button><button disabled={!active||active.kind!=='fence'} onClick={()=>insertOpening('wicket')}>Wstaw furtkę</button></div><small className="helper">Zaznacz odcinek ogrodzenia. Otwór zastąpi fragment przęseł; pozostała geometria zachowa pozycję.</small></section><div className="estimate-card"><div className="eyebrow">SZACUNEK MATERIAŁÓW</div><strong>{money(quote.total)}</strong><small>Ceny z katalogu brutto · bez montażu</small><button onClick={()=>setTab('quotes')}>Szczegóły wyceny <span>→</span></button></div></aside>
 </main>:tab==='products'?<main className="management"><div className="page-heading"><span className="eyebrow">KATALOG SYSTEMÓW</span><h1>Produkty</h1><p>Wybierz system do rysunku. Wymiary i ceny ustala sprzedawca w swoim panelu.</p><Link className="admin-link" href="/admin" target="_blank" rel="noopener noreferrer">Otwórz panel sprzedawcy →</Link></div><div className="catalog-grid">{catalog.map(p=><article key={p.id} className="product-card"><div className={`product-preview ${p.style}`}><div/>{Array.from({length:8},(_,i)=><i key={i}/>)}</div><h2>{p.name}</h2><p>Szerokość przęsła: {p.moduleWidth.toFixed(2)} m</p><strong>{money(p.price)} / {p.priceMode==='module'?'przęsło':'m'}</strong><p>Brama {money(p.gatePrice)} · furtka {money(p.wicketPrice)}</p><button onClick={()=>{change({...project,productId:p.id});setTab('project');}}>Użyj w projekcie →</button></article>)}</div></main>:<main className="management"><div className="page-heading"><span className="eyebrow">KALKULACJA / {project.name}</span><h1>Wycena materiałów</h1><p>{product.name} · wysokość {project.height.toFixed(2)} m · {quote.totalLength.toFixed(1)} m ogrodzenia i otworów</p></div><div className="quote-layout"><div><table><thead><tr><th>Element</th><th>Ilość</th><th>Wartość brutto</th></tr></thead><tbody>{quote.rows.map(r=><tr key={r.name}><td>{r.name}</td><td>{Number(r.quantity.toFixed(2))} {r.unit}</td><td>{money(r.total)}</td></tr>)}</tbody><tfoot><tr><td colSpan={2}>Razem</td><td>{money(quote.total)}</td></tr></tfoot></table><p className="helper">Kalkulacja orientacyjna: przęsła według ustawienia sprzedawcy (metry lub pełne moduły), słupki według szerokości modułów i wspólnych końców. Bramy i furtki według ceny za sztukę. Wysokość i kolor nie zmieniają ceny w tym modelu. Transport, montaż, fundamenty i automatyka wymagają osobnej wyceny.</p></div><aside className="quote-summary"><span className="eyebrow">PROJEKT DO KONSULTACJI</span><strong>{money(quote.total)}</strong><p>Pobierz geometrię i zestawienie materiałów do przekazania sprzedawcy.</p><button className="primary" onClick={downloadPdf}><Download size={16}/> Pobierz wycenę PDF</button><InquiryForm project={project} catalog={catalog}/></aside></div></main>}
 <footer className="statusbar"><span><span className="status-dot"/> {ready?'Projekt lokalny':'Wczytywanie'}</span><button className={snap?'snap-active':''} onClick={()=>setSnap(s=>!s)}>PRZYCIĄGANIE {snap?'ON':'OFF'} · 0,5 m</button><span>JEDNOSTKI: METRY</span><div/><button onClick={()=>{change({...initialProject,name:'Nowy projekt',segments:[]});setSelected(null);setTab('project');setView('2d');setStart(null);setDrawKind('fence');setPan({x:0,y:0});setZoom(1);setTool('draw');}}>Nowy projekt</button><button onClick={()=>upload.current?.click()}>Otwórz</button><button onClick={()=>download(project,'projekt-ogrodzenia.json')}>Eksport JSON</button><input ref={upload} hidden type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try {if(file.size>1000000)throw Error();const p:unknown=JSON.parse(await file.text());if(!isProject(p))throw Error();change(p);setSelected(null);setStart(null);setTab('project');notify('Wczytano projekt.');}catch {notify('Nieprawidłowy plik projektu. Wybierz eksport JSON z edytora.');}e.target.value='';}}/></footer>
 {message&&<div role="status" className="toast">{message}<button aria-label="Zamknij powiadomienie" onClick={()=>setMessage('')}><X size={14}/></button></div>}
 </div>;
}

